//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelfirstproje0205.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        public int ProjeNo { get; set; }
        public string ProjeAdi { get; set; }
        public string Aciklama { get; set; }
        public int CalisanSayisi { get; set; }
    }
}
